"""Add dia_saliente to ServicioFrecuente

Revision ID: 38efa697e984
Revises: b8d85ab1b38e
Create Date: 2026-01-21 14:38:59.326259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38efa697e984'
down_revision: Union[str, None] = 'b8d85ab1b38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicios_frecuentes', sa.Column('dia_saliente', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicios_frecuentes', 'dia_saliente')
    # ### end Alembic commands ###
