"""Add range columns to business models

Revision ID: 8f6118fa7250
Revises: 45efa697e984
Create Date: 2026-03-27 10:30:51.273886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6118fa7250'
"""Add range columns to business models

Revision ID: 8f6118fa7250
Revises: 45efa697e984
Create Date: 2026-03-27 10:30:51.273886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6118fa7250'
down_revision: Union[str, None] = '45efa697e984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Presupuestos (new table detected)
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('tipo_servicio', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuestos_id'), 'presupuestos', ['id'], unique=False)

    # 2. Add missing range columns to existing tables
    # Use execute to avoid errors if they already exist locally, or just add them
    op.execute("ALTER TABLE pedidos_individuales ADD COLUMN IF NOT EXISTS rango_horario VARCHAR")
    op.execute("ALTER TABLE pedidos_individuales ADD COLUMN IF NOT EXISTS rango_precio VARCHAR")
    op.execute("ALTER TABLE servicios_frecuentes ADD COLUMN IF NOT EXISTS rango_horario VARCHAR")
    op.execute("ALTER TABLE servicios_frecuentes ADD COLUMN IF NOT EXISTS rango_precio VARCHAR")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Remove range columns from existing tables
    op.execute("ALTER TABLE pedidos_individuales DROP COLUMN IF EXISTS rango_horario")
    op.execute("ALTER TABLE pedidos_individuales DROP COLUMN IF EXISTS rango_precio")
    op.execute("ALTER TABLE servicios_frecuentes DROP COLUMN IF EXISTS rango_horario")
    op.execute("ALTER TABLE servicios_frecuentes DROP COLUMN IF EXISTS rango_precio")

    # 2. Drop presupuestos table
    op.drop_index(op.f('ix_presupuestos_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    # ### end Alembic commands ###
