"""Add SesionTrabajo and Gasto

Revision ID: b8d85ab1b38e
Revises: 0001
Create Date: 2026-01-21 14:37:01.073700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d85ab1b38e'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('chofer_id', sa.Integer(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chofer_id'], ['choferes.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    op.create_table('sesiones_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chofer_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('total_horas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chofer_id'], ['choferes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_trabajo_id'), 'sesiones_trabajo', ['id'], unique=False)
    op.add_column('choferes', sa.Column('zona_gastos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choferes', 'zona_gastos')
    op.drop_index(op.f('ix_sesiones_trabajo_id'), table_name='sesiones_trabajo')
    op.drop_table('sesiones_trabajo')
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_table('gastos')
    # ### end Alembic commands ###
